version: '3'

volumes:
        mysql_volume:
                external: true
                
services:
        db:
                build: .
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                ports:
                        - 3306:3306
                        - 33060:33060
                environment:
                        MYSQL_ROOT_PASSWORD: example
                volumes:
                        - mysql_volume:/var/lib/mysql

        adminer:
                image: adminer
                restart: always
                ports:
                        - 8080:8080
                        

