version: '3'
volumes:
        influx_volume:
                external: true
services:
        influx:
                build: .
                ports:
                        - "7086:8086"
                volumes:
                        - influx_volume:/var/lib/influxdb

